### ISSUE TITLE
Dependence of OS when using ysfitsutilpy?

### ISSUE THREAD

**Issue by seonjae627** [ysBach/AO2019#12]
I am trying to install the ysfitsutilpy module in Windows. I am using anaconda/jupyter notebook for the python interpreter.
I followed the following code to install the module.

`$ cd <where you want to download this package>`
`$ git clone https://github.com/ysBach/ysfitsutilpy`
`$ cd ysfitsutilpy`
`$ python setup.py install`

Then the following error popped up, and I couldn't install the module.

` AttributeError: 'MSVCCompiler' object has no attribute 'compiler'`

I think the ysfitsutilpy module has dependencies with the fitsio module, but the fitsio module is not supported in Windows, only in UNIX operating systems. Windows only supports the cfitsio module, not fitsio. 
Is there any way to solve, or bypass this problem?

**Comment by ysBach** [comment]
@seonjae627 Thanks for reporting this issue.I wasn't aware of the OS dependency of fitsio installation.
I am now looking into this problem. Sorry for the inconvenience.

**Comment by ysBach** [comment]
@seonjae627 Thanks for your patience. I have updated ysfitsutilpy so that it doesn't "require" fitsio (but it may raise warning if you don't have it). DaJeong will announce the course takers about this issue. Sorry for the inconvenience --- I was unaware fitsio had OS dependency.... 

Please git pull ysfitsutilpy and reinstall it, reopen the Jupyter kernel, and let me know if it works. (I have tested the new one is installable and I could run first few notebooks on my old Win10 machine).

**Comment by ysBach** [comment]
I guess this has been resolved. Closing the issue.
Please reopen it if the problem persists.
