### ISSUE TITLE
Issue about hw07

### ISSUE THREAD

**Issue by seungukSong** [ysBach/AO2019#3]
1. In Problem 6 and 17. units of 'dark_300s' and 'stars' are already ADU. So, I think we don't need to divide them by gain_epadu
i.e.
in Problem 6
image_adu=dark_300s/? -> image_adu=dark_300s
in Problem 17
stars_adu = bias + (dark + sens*stars)/? -> stars_adu = bias + (dark + sens*stars)

2. There is a typo at Hint of Problem 7.
np.mean(dark) -> np.mean(dark_300s)

3. There is a typo at Problem 18
Save sens as a FITS file -> Save stars_adu as a FITS file

4. There is a typo at code of Problem 19
dark=top/"dark_300.fits" -> dark=top/"dark_300s.fits"

5. In windows, when I run the code at problem 22, [WinError 32] occurs because 'tmp\\bias.fits', 'tmp\\dark_300s.fits', 'tmp\\flat.fits', 'tmp\\image0001.fits', 'tmp\\image0001bdx.fits', 'tmp\\image0001bdf.fits' are opened. So we need to close this files before we delete them, but I couldn't find the method to close this files directly.
If we open this files as HDUlist, we can use '.close()' to close these files, but this code doesn't work on our code because we open these files as PrimaryHDU.
(I think there is a possibility that this error occurs only at windows.)
Temporarily I think I can manage this error by opening these files as HDUlist and change code from problem  17 to 21.

6. Problem numbers are need to be adjusted.
1. ~ 15. same
16. -> delete
17. -> 16.
18. -> 17.
19. -> 18.
20. -> 19.
21. -> 20.
22. -> 21.
below [4 points]
21. -> 22.
22. -> delete
below [4 points]
22. -> 23.

**Comment by ysBach** [comment]
> In Problem 6 and 17. units of 'dark_300s' and 'stars' are already ADU. So, I think we don't need to divide them by gain_epadu

Oh you're right. I forgot to remove "convert to ADU..." in Problem 5.... It won't affect your score as it's my fault, but I updated the problem (thus `dark_300s` in Problem 5 is in electron units, and thus Problem 16 also makes sense). Thanks!

> There is a typo at Hint of Problem 7. np.mean(dark) -> np.mean(dark_300s)
> There is a typo at Problem 18 Save sens as a FITS file -> Save stars_adu as a FITS file

You're right. Updated. Thanks.

> There is a typo at code of Problem 19 dark=top/"dark_300.fits" -> dark=top/"dark_300s.fits"

Oh this time I am right (yay) : `dark_300.fits` is the name of the FITS file you saved in problem 8. 

> In windows, when I run the code at problem 22, [WinError 32] occurs 

Oh that's correct. I just replaced problem 22 to "Delete your files and directory", so that you just manually delete the output files from this homework.

For the last comments
I dunno why the numberings are all messed up... Now updating.
